### ISSUE TITLE
unable to set server url

### ISSUE THREAD

**Issue by leonjza** [kestra-io/vscode-kestra#17]
I am trying to set the server URL that the plugin asks, but receive an error.

<img width="249" alt="image" src="https://github.com/kestra-io/vscode-kestra/assets/1148127/1d7ebee3-5c02-46e5-bb9f-ce58a8e3737c">

I have tried many combinations, including moving my dev environment running on localhost to a domain, adding `/api/v1` (and many variations thereof) with no success.

The vscode debug console shows this:

```
2024-03-11 18:13:22.250 [error] TypeError: Failed to parse URL from /plugins/schemas/flow
	at Object.fetch (node:internal/deps/undici/undici:11576:11)
	at async s.apiCall (.../.vscode/extensions/kestra-io.kestra-0.1.11/dist/web/extension.js:2:285081)
	at async .../.vscode/extensions/kestra-io.kestra-0.1.11/dist/web/extension.js:2:439716
	at async l.h (.../Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184831) kestra.schema.download {"value":"kestra-io.kestra","_lower":"kestra-io.kestra"}
```

**Comment by brian-mulier-p** [comment]
Fixed in [v0.1.12](https://github.com/kestra-io/vscode-kestra/releases/tag/v0.1.12), please reopen the issue if it persists :+1:
